### ISSUE TITLE
Error with the last command  " pip install curve25519-donna "

### ISSUE THREAD

**Issue by Rhomennik** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#1]
I already copied the In the right directory, the more time I execute the last command, it comes out
![captura](https://user-images.githubusercontent.com/24496303/43849907-8dc752ce-9b04-11e8-8d6e-1a9ee167dae9.PNG)

**Comment by romanzaikin** [comment]
I have wrote about that in the instruction, copy stdint.h to C:\Users\Administrator\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\bin\amd64

and run the pip command again.

**Comment by Rhomennik** [comment]
![image](https://user-images.githubusercontent.com/24496303/43850914-37df6560-9b07-11e8-9575-ff0d9a14189d.png)
I already copied stdint.h from the LIB folder

**Comment by hexadite-lior** [comment]
You should copy it to the VC\include directory instead.

**Comment by Rhomennik** [comment]
I managed to install by putting in the INCLUDE folder. Thank you both for helping me! Very thankful

**Comment by romanzaikin** [comment]
Thanks @hexadite-lior I mistakenly wrote the wrong folder in the readme...

**Comment by kidstell** [comment]
i had similar issue. look at the comment here for resolution
mukulhase/WebWhatsapp-Wrapper#211 (comment)
