### ISSUE TITLE
How to work with step 4 and 6 in Linux?

### ISSUE THREAD

**Issue by Jezwin** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#12]
download Microsoft Visual C++ Compiler for Python 2.7 at https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266

copy stdint.h to C:\Users\Administrator\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include

**Comment by Agusnez** [comment]
I have the same question but on macOS. But I have the feeling that on both could work.

**Comment by romanzaikin** [comment]
@Jezwin just skip the steps 4 and 6 and it should work...
