### ISSUE TITLE
web.whatsapp.com problems in finding public/private keys 

### ISSUE THREAD

**Issue by mahmoud0x01** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#13]
finding the web client **keypair** is hard in firefox i tried debugger and jsbeautify to set breakpoint but failed to get the keypair can you guys make a script to automate this step

**Comment by vishakhs1999** [comment]
Same issue even i had, but it used to work in google chrome, but now its not working there also i think whatsapp patched the vulnerability

**Comment by romanzaikin** [comment]
@vishakhs1999 just checked everything working in the same way...
@mahmoud0x01 currently we don't plan to do so, we have other plans :)

![capture](https://user-images.githubusercontent.com/11314384/43999797-464741d2-9e1c-11e8-933c-f9ee6a14fe09.PNG)

**Comment by NyleCohen** [comment]
i still dont understand how to get the public and private keys, can anyone make a step by step video/explanation on this??

**Comment by thiru112** [comment]
Do we have to add a breakpoint on that line "l.keypair" and make the script to run or add the breakpoint and execute it step by step??

**Comment by thiru112** [comment]
Atlast it's really simple follow these steps to get the private and public key 
1. Go to sources tab
2.search for line "l.keypair" 
3.u will find a line encode(t.pubkey) go to next line 
4.then click on line and add a *breakpoint*
5.then click Ctrl+R this time it will automatically go to that breakpoint and you will get the keys

**Comment by NyleCohen** [comment]
Thank you soooooo much for this answer. You are the first person to give a useful explanation on this topic. My only thing now is how to get the ref key if it is even necessary

**Comment by karmaishere** [comment]
It looks like you didn't read blog carefully.
"The keys can be obtained from the key generation phase from WhatsApp Web before the QR code is generated" Read line carefully "BEFORE THE QR CODE IS GENERATED"

**Comment by ghost** [comment]
does this still work?i am not seeing "l.keypair" in any line

**Comment by Bintang73** [comment]
> 1. l.keypair

Updated in January 2022

s.keyPair() in file qr js

>     96403: (e,t,r)=>{
        "use strict";
        var n = r(20862);
        Object.defineProperty(t, "__esModule", {
            value: !0
        }),
        t.getOrGenerate = function() {
            const e = a.getBundle();
            if ((null == e ? void 0 : e.key) && e.keyPair)
                return (0,
                i.encodeB64)(e.key);
            const t = s.keyPair()
              , r = (0,
            i.encodeB64)(t.pubKey)
              , n = {
                key: t.pubKey,
                keyPair: t,
                encKey: void 0,
                macKey: void 0
            };
            return a.set(n),
            r
        }
        ;
        var i = r(36117)
          , a = n(r(7125))
          , s = n(r(86109))
    }

**Comment by Bintang73** [comment]
you can find private key and public key before qr code is generated. you just need to debug and refresh the browser. you will find it...
