### ISSUE TITLE
Problem: "Bad message, can't decript the incoming message"

### ISSUE THREAD

**Issue by Sponge3** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#16]
Hello,
I can not decrypt a message intercepted with the burp suit proxy.
I turned the text into Base64.
The pair keys and the secret are correct.

**Comment by Sponge3** [comment]
Sorry for my bad language, but I'm a 13 years old Italian guy

**Comment by romanzaikin** [comment]
try different messages, maybe the message you try to decrypt is not really an incoming message.

**Comment by Sponge3** [comment]
Thank u, I'll try later because I can't use my pc now

**Comment by royalshape** [comment]
Same here. Converted text with Ctrl+B and get this error message after trying several messages. Connection to parser.py is OK.

**Comment by Sponge3** [comment]
Ok, resolved.
I didn't copy all the ref object.

**Comment by Sponge3** [comment]
Thanks

**Comment by CFlanc** [comment]
Same error for me no matter what I do, more over there's no way to tell you entered the correct secret code pubkey and privkey it gives you connected even if these are incorrect but I made sure mine where correct by following the guide TWICE and still got the same error no matter what.... And I am 100 percent sure that I am trying to decrypt the incoming message as when I press the forward button on burp suite for that message I received the message on WhatsApp web...

**Comment by royalshape** [comment]
@Sponge3 , where does ref object start and end?

**Comment by CFlanc** [comment]
`["Conn", {
	"ref": "1@SOMECODE/wP4JtcCP1WMA9v5/P6PRwFnn",
	"wid": "SOMECODE@c.us",
	"connected": true,
	"isResponse": "false",
	"serverToken": "1@SOMECODE+SOMECODE+EGZVLqBzDxKsRBDBJ3w==",
	"browserToken": "1@GCQ1vUkVACVDjGntMk+FctSOMECODEtMPXvWtS7H6t2e9/KrO21ZCX1GMGCAf62i+VmZS4VXUcIz4nCAi9U5m8XLkTVXGKAqZYUai/oVdF6m18EL1aY9H93QdeEnj5RKI90jcdUCKtsbcTDUTsZ0loXxQJhAQ==",
	"clientToken": "SOMECODE/SOMECODE+oo=",
	"lc": "US",
	"lg": "en",
	"secret": "SOMECODE++SOMECODE",
	"protoVersion": [0, 17],
	"binVersion": 10,
	"battery": 36,
	"plugged": false,
	"platform": "android",
	"features": {
		"URL": true,
		"FLAGS": "GAEoATgB"
	},
	"phone": {
		"wa_version": "2.18.247",
		"mcc": "420",
		"mnc": "001",
		"os_version": "8.0.0",
		"device_manufacturer": "SOMECODE",
		"device_model": "SOMECODE",
		"os_build_number": "SOMECODE-SOMECODE 8SOMECODE0.0.376(C185)"
	},
	"pushname": "\SOMECODE\u0628\u062f \u0627\SOMECODE\u0644\u0647 \u0646\u0633SOMECODEu064a\u0645",
	"tos": 0
}]`

**Comment by Banginpadr** [comment]
@CFlanc @Sponge3 bro i had been trying for days to get mine to work, would you please be so kind to help me? i cant decrypt mines. i dont know what im doing wrong do you have kik or dicord?

**Comment by CFlanc** [comment]
Telegram : @Deadly6o i just figured out mine and it works like charm now....

**Comment by Banginpadr** [comment]
@CFlanc hi bro would you be so kind to tell me how you did it? i have everything set up right but i cant make it work

**Comment by Banginpadr** [comment]
@Sponge3 fra tu hai kik o discord? ho bisogno di aiuto pure io come te ho le chiavi e tutto messo bene ma non mi funziona non lo so perche

**Comment by Banginpadr** [comment]
@CFlanc bro your worked? when i send my edited message it never get to the person i want it to get

**Comment by Sponge3** [comment]
@CFlanc your ref object doesn't contain the secret code

**Comment by Sponge3** [comment]
You must follow this guide https://research.checkpoint.com/fakesapp-a-vulnerability-in-whatsapp/

**Comment by Sponge3** [comment]
Watch also the video

**Comment by Sponge3** [comment]
@Banginpadr su discord sono sempre Sponge3

**Comment by Sponge3** [comment]
@Banginpadr su discord #0189Sponge3

**Comment by romanzaikin** [comment]
I see that the problem, solved. 
If you have more questions you can open a new issue.

**Comment by Code-Chapter** [comment]
I don't know why but im getting the same error too. My ref object param starts with: `{"ref":"1@...` and ends with `"tos":0}`. My priv key and public key end with `201, 189, 244, 110] ` and `36, 186, 189, 67, 87]` respectivly. When i try decrypt or even encrypt a message it says bad message cant decrypt or cant encrypt message something wrong with the data. how could i solve this?
