### ISSUE TITLE
Encrypting decrypted message result in different message from original

### ISSUE THREAD

**Issue by johntiror** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#17]
Hi,

I'm having trouble changing the message content. I'm able to intercept the message and deprypt it. Once I modify the message (as in the video) I then press "Encrypt", I copy in the proxy, base64 decode it, but then the message does not appear in my web.whatsapp

I noticed that if I intercept a message, then decrypt and immediately encrypt (without any modification) if I compare the original message and the decrypted/encrypted one they are different. I expect them to be the same. Maybe there is a problem in the encryption?

Thanks

**Comment by romanzaikin** [comment]
@johntiror the message you write is in English? 

Try to decrypt/encrypt same message and check if it works.
Try to change 1 character, add characters or remove characters.

**Comment by Banginpadr** [comment]
@johntiror bro how did you get to decrypt it? i have the keys and the right ref but i keep getting error mine doesnt get decrypt.

**Comment by max194** [comment]
@Banginpadr before copying it you need to press ctrl + b, after pasting it you need to press ctrl + shift+ b (encoding and decoding as base64)

**Comment by Banginpadr** [comment]
@max194 max you are a good thank you so much. i just fix this problem to just find another one.. after i edit the messagge and crypt it again and past it to be send the message dont get send

**Comment by Banginpadr** [comment]
@max194 i do just as you said. but after i send the message it get lost. it never get to the chat. first ctrl + b, past it to get decryt after is decrypt and edit, i past it agan to where i took the orginal and click foward. but nothing happen the message get lost

**Comment by Banginpadr** [comment]
@max194 im just having the same problem jhon is having i dont know why

**Comment by johntiror** [comment]
Why did you close it? My issue is still there as shown in the pictures

**Comment by Banginpadr** [comment]
@romanzaikin this is what im talking about. this is what i did. but in the replay the message is still the original

**Comment by romanzaikin** [comment]
@johntiror can you check now? I have fixed it in the new parser file
