### ISSUE TITLE
Edited message only happening on my side

### ISSUE THREAD

**Issue by Banginpadr** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#22]
i did everything just as in the blog. everything is working like a charm BUT whenever i edit a message, im the only person that can see it. the others get the original message. EXAMPLE; a person in my group write "red" and i edit it to "blue" im the only one that see it.

**Comment by Sponge3** [comment]
Ho discord #0189Sponge3

**Comment by Banginpadr** [comment]
@romanzaikin this is what i do. i spoof my friend message then when i see it in the chat i replay to it to make it seem like im replaying to what ever he is saying. but still the message never get spoof. ima keep playing with it tho

**Comment by Banginpadr** [comment]
@Sponge3 fra non ti trovo cercami tu Banginpadr#7942

**Comment by Sponge3** [comment]
What are the three parameters?
Id, timestrap and ....
What I need to change, what number or letter??

**Comment by Banginpadr** [comment]
@romanzaikin i tried that once but i didnt work. i can just make one up? like just changing one letter or something. @Sponge3 fra ti ho scritto anzi ti ho mandato la riquesta di amicizia ma non mi hai risposto

**Comment by romanzaikin** [comment]
@Sponge3 read our blog... and if you have issues describe your steps.

https://blog.checkpoint.com/2017/03/15/check-point-discloses-vulnerability-whatsapp-telegram/
