### ISSUE TITLE
Changing incoming message content with Unicode characters doesn't work

### ISSUE THREAD

**Issue by avivyel** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#23]
I have configured everything correctly, and successfully spoofed incoming group message contents, as long as the messages were in English.
When I tried to do the same process for an incoming message in Hebrew (decrypt, change message content, encrypt and forward through Burp's proxy) that contained special characters with '\u' - the spoofed message just didn't show in WhatsApp Web.

**Comment by romanzaikin** [comment]
@avivyel you can use online website in order to write in unicode, for example:

https://www.branah.com/unicode-converter

If more people will ask for it, I will add that in the tool.
