### ISSUE TITLE
Outgoing Decryption of long messages doesn't work

### ISSUE THREAD

**Issue by johntiror** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#25]
If you encrypt a long outgoing message it seems to work, but then you're unable to decrypt it. 
Here the steps:

Outgoing message ready to be decrypted:
<img width="964" alt="schermata 2018-08-16 alle 09 03 14" src="https://user-images.githubusercontent.com/3677019/44193553-903b2780-a133-11e8-8767-d91a097b50f0.png">

Message decrypted:
<img width="967" alt="schermata 2018-08-16 alle 09 03 19" src="https://user-images.githubusercontent.com/3677019/44193563-96c99f00-a133-11e8-987b-f93ddacea3cc.png">

Message modified to be long:
<img width="986" alt="schermata 2018-08-16 alle 09 03 35" src="https://user-images.githubusercontent.com/3677019/44193577-a2b56100-a133-11e8-9c30-24f975891402.png">

Message encrypted:
<img width="962" alt="schermata 2018-08-16 alle 09 03 40" src="https://user-images.githubusercontent.com/3677019/44193583-aa750580-a133-11e8-808e-892ab39f3fcf.png">

Decryption now doesn't work, the parser.py script will throw an exception and close itself:
<img width="571" alt="schermata 2018-08-16 alle 09 04 00" src="https://user-images.githubusercontent.com/3677019/44193604-c1b3f300-a133-11e8-8c86-f5777e2b78d3.png">

**Comment by romanzaikin** [comment]
I have fixed that :)
