### ISSUE TITLE
Decryption of an outgoing reply message doesn't show the message

### ISSUE THREAD

**Issue by johntiror** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#26]
If I try to decrypt an outgoing reply message:

<img width="1008" alt="schermata 2018-08-16 alle 09 10 19" src="https://user-images.githubusercontent.com/3677019/44193833-79e19b80-a134-11e8-9227-1310c27a8a6f.png">

here the reply message ready to be decrypted:
<img width="982" alt="schermata 2018-08-16 alle 09 11 36" src="https://user-images.githubusercontent.com/3677019/44193841-82d26d00-a134-11e8-9574-883fd1d68655.png">

here the reply message decrypted:
<img width="976" alt="schermata 2018-08-16 alle 09 11 41" src="https://user-images.githubusercontent.com/3677019/44193852-8c5bd500-a134-11e8-8674-0754f546ed31.png">

as you can see the message field is empty: it should not.

**Comment by thiru112** [comment]
@johntiror how to get the ref object .though I intercept I can't see the websockets history tab in burp suite help me

**Comment by romanzaikin** [comment]
@johntiror I have fixed it, can you check please?

**Comment by thiru112** [comment]
@romanzaikin  i am able to decrypt outgoing msg, but again  when i try to encrypt it chows error message
Before decryption outgoing message:
![screenshot from 2018-08-21 23-36-08](https://user-images.githubusercontent.com/34017131/44420364-50dd6280-a59b-11e8-8216-705874a9bf90.png)
After decryption of outgoing message:
![screenshot from 2018-08-21 23-42-09](https://user-images.githubusercontent.com/34017131/44420556-e2e56b00-a59b-11e8-93ff-81d05bdd212e.png)

Again trying to encrypt:
![screenshot from 2018-08-21 23-37-53](https://user-images.githubusercontent.com/34017131/44420423-81bd9780-a59b-11e8-9289-70aa3c44a9a6.png)

**Comment by romanzaikin** [comment]
@thiru112 do you use the new code I have uploaded? because I just fixed this issue.

**Comment by thiru112** [comment]
@romanzaikin 
Thanks,you new code problem solved.
**Sorry for saying this again but, when i try to decrypt the encrypted message again it shows error again.**
Before decryption 
![screenshot from 2018-08-23 11-11-29](https://user-images.githubusercontent.com/34017131/44506925-35bb4180-a6c6-11e8-900c-87fec533b501.png)
After Decryption:
![screenshot from 2018-08-23 11-11-37](https://user-images.githubusercontent.com/34017131/44506933-42d83080-a6c6-11e8-8e3d-851c3df83e2c.png)
Encrypting the same message:
![screenshot from 2018-08-23 11-11-49](https://user-images.githubusercontent.com/34017131/44506967-6602e000-a6c6-11e8-871e-35276ef7cb9a.png)
Decrypting the above encrypted message:
![screenshot from 2018-08-23 11-12-05](https://user-images.githubusercontent.com/34017131/44506998-7fa42780-a6c6-11e8-94cb-71afd0e775ab.png)

**Comment by johntiror** [comment]
@romanzaikin I just tested the latest code and still the message field is empty in case of reply.

![schermata 2018-09-01 alle 09 59 00](https://user-images.githubusercontent.com/3677019/44943868-b4eafc80-adcd-11e8-9218-7b162fd96c18.png)

Be aware of a possible confusion: this issue is related to the message field empty in case of a reply, it's not related to errors in encryption/decryption. So I think it's not correct to reference the issue "Randomly outgoing encryption does not work #24" to this one. Also the @thiru112 post is off topic here.

Thanks

**Comment by thiru112** [comment]
@johntiror I had this **empty message** field when I tried with different mobile phones, like my mom had vivo when I tried same n times it had same issue (empty field). But my MI phone doesn't show this empty message field at all.
