### ISSUE TITLE
Cant get whatsapp web qr code when burp is listening.

### ISSUE THREAD

**Issue by NyleCohen** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#27]
Hi!

I am trying to get the websocket from burp by scanning  the qr code on [whatssap web](web.whatssap.com) but when I set burp to listen to the browser the qr code doesnt load. I have tried this on chrome and firefox. If anyone could help me that would be great.

Thank you
Nyle

**Comment by Banginpadr** [comment]
bro you dont have to have burp listening when you are trying to get the qr code. you only doit it after you get the keys. i have discord banginapdr7249 if you want me to help you

**Comment by NyleCohen** [comment]
How do you get the secret parameter that they described in the blog post?

**Comment by Banginpadr** [comment]
all you have to do is open chrome debugger and search for the ", n(or a) =" highlight it and thats it. it will give you what you need. but is useless if you dont really know how to use this program at all. that is the easier part of all this. the really hard part at least for me is understanding how to spoof messages ect

**Comment by thiru112** [comment]
@NyleCohen I to had the same problem, if we set u proxy then the QR code doesn't load at all
By removing proxy it got loaded

**Comment by romanzaikin** [comment]
@NyleCohen just read @Banginpadr comment.
