### ISSUE TITLE
Not able to get Keys in Firefox

### ISSUE THREAD

**Issue by thiru112** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#28]
though the priv key and pubkey appear cannot get the values in the array
![screenshot from 2018-08-19 10-51-27](https://user-images.githubusercontent.com/34017131/44305793-6174b980-a39e-11e8-83dd-4cd36e1d7028.png)

**Comment by thiru112** [comment]
@Banginpadr lol okay then I will close this issue

**Comment by Banginpadr** [comment]
@thiru112 just let me know if you make it work. i did everything just as they say in the blog but it doesnt work. i mean i get to edit the messages and everything but when i send them, im the only person to see it not the others in their phones

**Comment by thiru112** [comment]
@Banginpadr i too have the same problem it changes only in my side(attacker) but not on other side(victim) i am also getting confused

**Comment by thiru112** [comment]
@Banginpadr Bro the problem was with us.
The Blog clearly stated that we had to change **the ID param** 

For Example:

this was my ID
 "id": "DAB0AD75C5EAC92C139F5A4E2D86086C"

I changed it to
 "id": "DAB0AD75C5EAC92C139F5A4E2D86086**D**"

Now it works properly.
This problem was because the WhatsApp Database already stored the Message with an ID, and we can't make modifications to it.

Hope this Helped.

**Comment by Banginpadr** [comment]
@thiru112 you have to change the victim ID or your ID before sending the message? thank you for your help

**Comment by thiru112** [comment]
@Banginpadr 
 the victim Id is known as **remote jid**  you should not change this.
there will be parameter called **id**  this is message id which is stored in database ,we should change this id only

**Comment by Banginpadr** [comment]
@thiru112 ooooh now i got it thank you so much bro

**Comment by thiru112** [comment]
@Banginpadr Welcome bro
