### ISSUE TITLE
A better way to translate the json to list

### ISSUE THREAD

**Issue by andrekorol** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#29]
On parser.py there are some TODOs where it's said that a better way to translate the json to list is needed.
Isn't it possible to just use json.loads() instead of ast.literal_eval() ?

**Comment by andrekorol** [comment]
I may be wrong, but I think you could also use json.loads on data["data"]["msg"] instead of ast.literal_eval.
And by doing that you would get the correct True and False values.

**Comment by Banginpadr** [comment]
@andrekorol bro just make a pull requests for us?

**Comment by andrekorol** [comment]
Yeah, of course, I can make a pull request. I'd be glad to help! But do you have any sample of that json data I could test with?
If not, I guess I'll just try with real world data by using the extension with my modifications.

**Comment by Banginpadr** [comment]
no bro no data. sorry

**Comment by andrekorol** [comment]
I'm sorry, are you being sarcastic?

**Comment by Banginpadr** [comment]
no bro

**Comment by thiru112** [comment]
@andrekorol  You can't get private and public keys using burp suite

you have to get it using debugger in chrome

you can get **ref object**  using burpsuite

**Comment by thiru112** [comment]
@andrekorol Follow this process to get  keys

https://github.com/romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint/issues/13#issuecomment-413752900

**Comment by Banginpadr** [comment]
@andrekorol yeah bro just use chrome, after you have the keys thats when you should start burp
