### ISSUE TITLE
Decrypt-Encrypt-Decrypt on outgoing message not working

### ISSUE THREAD

**Issue by tarun14110** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#34]
I decrypted my outgoing message. And encrypted it without editing. On trying to decrypt it again, I get error. 
And I am getting different encrypted message after re-encrypting the same message.

Original outgoing message
![screenshot from 2018-09-24 08-02-41](https://user-images.githubusercontent.com/12219700/45936093-53830b80-bfd0-11e8-86bb-3681ae13b28f.png)

Decrypted outgoing message
![screenshot from 2018-09-24 07-46-43](https://user-images.githubusercontent.com/12219700/45936034-7c56d100-bfcf-11e8-85cf-3a4fd693d0b4.png)

Encrypted outgoing message (without any changes)
![screenshot from 2018-09-24 07-46-48](https://user-images.githubusercontent.com/12219700/45936035-7cef6780-bfcf-11e8-95af-f4a569d4226d.png)

Trying to decrypt it
![screenshot from 2018-09-24 07-46-52](https://user-images.githubusercontent.com/12219700/45936037-7cef6780-bfcf-11e8-90f0-e7031ebef5f7.png)

**Comment by thiru112** [comment]
@tarun14110 I also had same issue and posted that if you find solution ,let me know

**Comment by tarun14110** [comment]
@thiru112 So, were you able to impersonate outgoing messages as other user (attack #2 as explained on blog)?

**Comment by thiru112** [comment]
@tarun14110  I wasn't able to change message an put into the **'a'** parameter in the browser

**Comment by tarun14110** [comment]
You can do that by using this code `a = Uint8Array.from([new encrypted array]).buffer` at console during breakpoint at and then continue .
But, its not working. I guess there is some issue with encryption for outgoing messages. The encryption method should encrypt the decrypted outgoing message to same message as before decryting. But it's not doing that for now.

**Comment by thiru112** [comment]
@tarun14110 I try and reach you asap

**Comment by ertzaaafzal** [comment]
Hi all, I'm having the same issue except that I'm trying for **incoming** message. When I decrypt the message and then re-encrypt it (even without making any changes in the message) - this newly encrypted message cannot be decrypted so ofcourse when I forward it to whatsapp web, it is not able to decrypt it and show it. I hope someone can help fix it soon.

**Comment by GinNoel** [comment]
> 
> 
> You can do that by using this code `a = Uint8Array.from([new encrypted array]).buffer` at console during breakpoint at and then continue .
> But, its not working. I guess there is some issue with encryption for outgoing messages. The encryption method should encrypt the decrypted outgoing message to same message as before decryting. But it's not doing that for now.

@thiru112 did you manage to get this work.  I'm stuck on how to chage it in the browser.

Hi,

This is regarding Attack 2.

I manage to decrypt outgoing message.
Change the message, change true to False.
Encryp it back successfully.

I'm stuck on putting the encrypted data back to the console. I.e. im stuck on no 4 (please see attached image). How can I do that?

Thank you

<img width="706" alt="ss1" src="https://user-images.githubusercontent.com/45450873/49521070-88b8ad80-f8df-11e8-9b63-971507bac185.PNG">

**Comment by GinNoel** [comment]
> 
> 
> You can do that by using this code `a = Uint8Array.from([new encrypted array]).buffer` at console during breakpoint at and then continue .
> But, its not working. I guess there is some issue with encryption for outgoing messages. The encryption method should encrypt the decrypted outgoing message to same message as before decryting. But it's not doing that for now.

Hi @tarun14110 did u manage to get the  `a = Uint8Array.from([new encrypted array]).buffer` work?

**Comment by Orinion** [comment]
@GinNoel sorry for the late reply but i managed to do it.
first create a global variable in the console.
`temp = new Uint8Array([248,..., 2, 1]).buffer`
then doubleclick the a variable in the local scope and insert the name of the global variable.
![override](https://user-images.githubusercontent.com/12730894/53436465-8d32c500-39fb-11e9-9727-399b382d3031.JPG)

**Comment by ZRginger** [comment]
Hello, can anyone fix the problem? Letting DE-EN-DE on outgoing message works well.

**Comment by GinNoel** [comment]
> 
> 
> @GinNoel sorry for the late reply but i managed to do it.
> first create a global variable in the console.
> `temp = new Uint8Array([248,..., 2, 1]).buffer`
> then doubleclick the a variable in the local scope and insert the name of the global variable.
> ![override](https://user-images.githubusercontent.com/12730894/53436465-8d32c500-39fb-11e9-9727-399b382d3031.JPG)
> 
> Also note that the encrypted message is not correct (for me it inserts a 11, however after removing it, it works)

Hi @Orinion ,

My apologies for the very late reply.  Thank you for the steps.

You lost me here "(for me it inserts a 11, however after removing it, it works)".  Can you please explain further?

Thank you.

**Comment by Orinion** [comment]
Hello, taken frome the screenshots of the op:
![grafik](https://user-images.githubusercontent.com/12730894/57792137-9d2a8d00-773e-11e9-80b9-2a74baf5054c.png)
he didn't change annything, however the 11 gets added after encrypting. Simple remove it again
