### ISSUE TITLE
Trying to figure out how to pull up the extension

### ISSUE THREAD

**Issue by Arb1993** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#35]
I'm just at the point where I'm trying to pull up the BurpSuite Extension so I get the box with all the tabs like how it looks in all of the blog example pictures. I'm (pretty sure ish?) that I ran the parser.py file and burpWhatsapp.py to my extensions....although tbh I don't even totally understand that and maybe I didn't. Anyways. I desperately need help just getting this extension to appear. Thank you.

**Comment by thiru112** [comment]
@Arb1993 If you want to run python extension in Burp suite you need download **Jython standalone.jar** file
 
Use this link to download:
[http://search.maven.org/remotecontent?filepath=org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar](url) 

1.Open Burp .Go to **Extender tab**

2.Click **options** in below sub stabs

3.you will see **python environment** 
 it will show _Location of Jython standalone_

4.click select file button and choose the download        Jython standalone.jar file

5.In same Extender tab you will see extensions sub tab(the sub first tab in Extender tab)

6.Now click add select **Extension type** as python select the burpWhatsapp.py and click next

7.Now it will run and you will get a new tab called **WhatsApp decoder**

**Comment by fuxf1984** [comment]
@thiru112 thanks for your reply. But I would like to ask, how do I run parser.py? Thanks for the help
