### ISSUE TITLE
Getting secret parameter with Burp

### ISSUE THREAD

**Issue by deepakdaswani** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#36]
Hi guys. I am trying this extension and I could retrieve my public and private keys debugging Javascript code following the instructions on the technical post. But I have some problems with the "secret" parameter.
As the post says, it's the mobile phone who makes the request to web.whatsapp.com so you have to set Burp to capture that traffic. I'm using and iPhone X with iOS 11.4. I set the proxy manually and installed the PortSwigger cert via a profile in the phone. 
But I can't get any HTTPS request made by WhatsApp on Burp. Not in the history tab neither in the websockets tab. I do see other HTTPS requests made with the browser. 
Could you help me to understand what is wrong? 
I imagine this parameter can only be retrieved from that request.
Thanks for your help and congratulations @romanzaikin for the research and the job. It's pretty cool!

**Comment by thiru112** [comment]
@deepakdaswani try start browser with proxy in command line mode that is ,

`google-chrome --proxy-server="127.0.0.1:8080" ` 

because i too had the same issue. i can see the https request but there where no entries in websocket history

**Comment by thiru112** [comment]
@deepakdaswani the other way to retrieve the secret parameter by using this below method

https://github.com/romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint/issues/20#issuecomment-414528328

**Comment by deepakdaswani** [comment]
Thank you for your fast reply @thiru112 . I was a bit confused because in the post it says that the request is sent by the mobile phone  , not by the browser itself.
For the Burp extension to work, you have to configure the proxy manually in the phone. But , do you need to install the PortSwigger certificate?

**Comment by thiru112** [comment]
@deepakdaswani First of all you don't need to configure proxy in your mobile phone. below set will happen when you scan the QR code

1.the mobile phone will say "hey man we are going to communicate each other . you can identify me by this **secret parameter** ".

2.the mobile phones sends the secret parameter to browser.

3.we are going to capture the secret parameter in burp suite by intercepting, or you can get that parameter using developer tools in chrome also


you need to install certificate only in computer browser not in your mobile phone.

**Comment by deepakdaswani** [comment]
Thanks for the reply @thiru112 ! I figured out after seeing your first reply. I will try when I can to make it work. So the messages that you intercept are all from the web session. Thanks!

**Comment by thiru112** [comment]
@deepakdaswani if your problem is resolved close this issue , thank you

**Comment by deepakdaswani** [comment]
Sorry @thiru112 I still have not been able to try this again. I will close the issue and reopen it if have anything to ask. Thanks and sorry for the late reply :(
