### ISSUE TITLE
Decrypting incoming message works but manipulation is not made 

### ISSUE THREAD

**Issue by deepakdaswani** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#38]
Hi everybody. Do the attacks described in the post still work? I finally was able to set up the ref object, the keys, run the parser, connect to the extension and I can successfully decrypt an incoming message. 

![image](https://user-images.githubusercontent.com/6955980/47304401-7419a200-d61e-11e8-8527-188e80d201cf.png)

But when I change the content of the message, even though I change the id to anything else (like it says in the post) and also the timestamp, when I encrypt it and paste it again in the intercept tab after clicking ctrl-shift-B it does not reach modified. 

In the post you can see that you can do this for group messages but the first scenario in the video the attacker could spoof any incoming message in and individual chat. I have tried both ways. Individual chat and group chat. I can decrypt the message , but when I changed it and I can paste it and forward the request I cannot see the spoofed message.

Thanks to all of you for your reply! Thanks @romanzaikin  for the great work!

**Comment by thiru112** [comment]
@deepakdaswani It worked perfectly before for me. I don't know why it's not modified. I will check reply you later

**Comment by deepakdaswani** [comment]
Hi @thiru112 . Could you try this? I did many tests and when I sent the modified message it never reached the web session. Till today, I tried and only once I could do it and change the original message. But after trying to do it 10 or 20 times with messages from different people, I have only been able to do it once.. Don't know why. It has something to do with the "id" when you change it. That id it's sometimes 20 characters, others 32 (16 bytes).
I imagine that I cannot change it for one that is already in the database. So I try to pick different ids randomly changing some digits. But do you know if you have to put a older or newer id?
