### ISSUE TITLE
Problem with outgoing message

### ISSUE THREAD

**Issue by shurpizza** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#4]
I'm trying to set the outgoing message by modifying the ‘a’ parameter in the browser with this function

```
var f = function str2unit8(str) {
  var buf = new ArrayBuffer(str.length);
  var bufView = new Uint8Array(buf);
  
  for (var i=0, strLen=str.length; i < strLen; i++) {
    bufView[i] = str[i];
  }
  return buf;
};
```

How do I modify the parameter. Like:

1. `a = f("[ ... ]");`
or
2. `a = f([ ... ]);`

And it's necessary to change anything else from this code besides `fromMe `to false?

`["action", {"epoch": "293", "type": "relay"}, [{"message": {"conversation": "d"}, "messageTimestamp": "number", "key": {"fromMe": true, "remoteJid": "number@s.whatsapp.net", "id": "number"}, "status": "PENDING"}]]`

**Comment by romanzaikin** [comment]
It's the second one, and about your question, what do you mean? I will not teach you how to spoof messages or something.

Use this tool to investigate the protocol and find bugs by your own, LOL
