### ISSUE TITLE
PubKey-PrivKey-Secret-RefObject

### ISSUE THREAD

**Issue by GinNoel** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#40]
Hi All,

I'm trying to understand the difference between the 4 attributes: private Key, public key, ref object and secret.

I know the private key, public key and ref object are to be place at the burp suite extension.

However, why do i need the secret (as shown in the image below)
<img width="547" alt="ss1" src="https://user-images.githubusercontent.com/45450873/49208296-5ea05080-f3f2-11e8-9f3e-7edb4a4d4f39.PNG">

Do I need to place the secret key somewhere within the burp suite?

Thank you.

regards,
GinNoel

**Comment by thiru112** [comment]
@GinNoel No u don't need place secret key anywhere only private,pubic key and ref object are enough

**Comment by thiru112** [comment]
@GinNoel when you have all three objects priv,pub key, ref object you can **click CONNECT** button .After you click you can decrypt and encrypt messages. you nee click CONNECT only  once

**Comment by GinNoel** [comment]
Thank you @thiru112. I will give it a go in that particular order.

Fyi, I did manage to decrypt incoming text. But got a bad error message when I try to decrypt it back regardless I change the text or not.

**Comment by thiru112** [comment]
@GinNoel Can you send screenshot so I can help you , on your error

**Comment by GinNoel** [comment]
Hi @thiru112 ,

Here is what i did.

Copy public, privkey and ref object.
Connect successfuly.
Intercept incoming message successfully.
Encode it to base64, copy it and pasted it in WhatsApp decoder
I clicked on incoming button.
Click Decrypt. And it decrypt successfully.
I change the message (only) and click encrypt. This works.
I copy and paste it back to intercept tap within gthe proxy tab.
decode it. and click forward button.

Nothing change.

When i hover my cursor on the field box (within Whatsapp decoder), a msg shows "if you putting in the incoming traffic you can copy it from burp suite, the outgoing is the list from aesCbcEncrypt"  ,-- what is this refering to?

Regards,
GinNoel

**Comment by thiru112** [comment]
@GinNoel 

Nothing will change, if you don't change some parameters.
you have to change these parameters,
 
**message timestamp** - for eg 1533030936 to 1533030945.

**Id** - for eg the long hex value change the last two hex values

now  you will able to see the changed message.

**Read the blog carefully the above mentioned points are given in blog**

**Comment by thiru112** [comment]
@GinNoel 
the hover says the parmaters to put in the box

if incoming msg put the base64 encode.
if you going put aescrypt parameter

**Comment by GinNoel** [comment]
> 
> 
> @GinNoel
> 
> Nothing will change, if you don't change some parameters.
> you have to change these parameters,
> 
> **message timestamp** - for eg 1533030936 to 1533030945.
> 
> **Id** - for eg the long hex value change the last two hex values
> 
> now you will able to see the changed message.
> 
> **Read the blog carefully the above mentioned points are given in blog**

Thank you @thiru112 

As for outgoing, I would assume the outgoing button is for all messages that I'm sending out.  The incoming is for all incoming messages to my number.

I noticed when I click on the Outgoing button, and wanted to decrypt a base64, I always get the "error; "bad message, can't decrypt the outgoing message"

Decrypting and encrypting incoming message is fine

**Comment by GinNoel** [comment]
> if you going put aesCbcencrypt parameter

What do you mean by "if you going put aesCbcencrypt parameter"?

**Comment by GinNoel** [comment]
> > @GinNoel
> > Nothing will change, if you don't change some parameters.
> > you have to change these parameters,
> > **message timestamp** - for eg 1533030936 to 1533030945.
> > **Id** - for eg the long hex value change the last two hex values
> > now you will able to see the changed message.
> > **Read the blog carefully the above mentioned points are given in blog**
> 
> Thank you @thiru112
> 
> As for outgoing, I would assume the outgoing button is for all messages that I'm sending out. The incoming is for all incoming messages to my number.
> 
> I noticed when I click on the Outgoing button, and wanted to decrypt a base64, I always get the "error; "bad message, can't decrypt the outgoing message"
> 
> Decrypting and encrypting incoming message is fine

Hi @thiru112 ,

I managed to successfully manipulate incoming messages. Thank you for the clarification.

Will try to test the other scenario.

Thank you

**Comment by tech-white** [comment]
@thiru112  A noob here, stuck with key gathering. Help?

**Comment by tech-white** [comment]
Or in case you might've taken down the process you followed, in much simpler format? @thiru112
