### ISSUE TITLE
Attack 2 not working

### ISSUE THREAD

**Issue by Kitcha123** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#43]
Hi,
I am not able to put back the encrypted data via console. Please tell it step by step.

Also, after encrypting the message, if I try to decrypt it again (ie: decrypt-encrypt-decrypt of outgoing message) it throws error. Why?

Please provide a reply.

**Comment by pctripsesp** [comment]
> Hi,
> I am not able to put back the encrypted data via console. Please tell it step by step.
> 
> Also, after encrypting the message, if I try to decrypt it again (ie: decrypt-encrypt-decrypt of outgoing message) it throws error. Why?
> 
> Please provide a reply.

Did you get new Keys for attack 2? note there aren't the same as in Attack 1

**Comment by pctripsesp** [comment]
same as #34

**Comment by Orinion** [comment]
Here is a step by step tutorial:

- open web.whatsapp, select a private chat you want to fake
- enter a text that you want to appear, as if sent by the other person
- open the debugger with ctrl + shift + i
- find the method in "app2." by searching for "aesCbc" and set a breakpoint
- click send
- in the local namespace you should now have an ArrayBuffer object with the name a
- expand the uint version so you see each element.
- at index 48 there should be a "1"
- change it to a 0 by double clicking on the 1.
- remove the breakpoints
- click "resume sctipt"

**Comment by GinNoel** [comment]
Hello Orinion,

Works perfectly for private chat.  I do however, came up with problems changing from 0 to 1 where the 0 is not edit-able.  But i'm sure this is the browser issue.

Thank you for the step-by-step guide. 

> Here is a step by step tutorial:
> 
> * open web.whatsapp, select a private chat you want to fake
> * enter a text that you want to appear, as if sent by the other person
> * open the debugger with ctrl + shift + i
> * find the method in "app2." by searching for "aesCbc" and set a breakpoint
> * click send
> * in the local namespace you should now have an ArrayBuffer object with the name a
> * expand the uint version so you see each element.
> * at index 48 there should be a "1"
> * change it to a 0 by double clicking on the 1.
> * remove the breakpoints
> * click "resume sctipt"
