### ISSUE TITLE
once i got the private and public key the QR CHANGE itself

### ISSUE THREAD

**Issue by silverar** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#46]
im using the BREAKPOINT to catch the PRIVATE+PUBLIC key . but when i resum the debugger to show the QR. the QR will change itself multiple times .

**Comment by Orinion** [comment]
Hello,
when you hit the breakpoint, there should be no qr code yet.
The fact that the QR code changes does not matter, the keys stay the same as long as you don't refresh the site before scanning it.

**Comment by silverar** [comment]
> Hello,
> when you hit the breakpoint, there should be no qr code yet.
> The fact that the QR code changes does not matter, the keys stay the same as long as you don't refresh the site before scanning it.

As you said we make a breakboint then i refresh the page so it hit the breakpoint and no QR will be there . then resume the debugger to get the QR.
