### ISSUE TITLE
How to use AesCbcEncrypt?

### ISSUE THREAD

**Issue by ZRginger** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#48]
Hi, can some one tell me how to decrypt the outgoing message in aescbcencrpt. Actually I only find a plugin called AES kill. 
@Orinion Can you help me please?

**Comment by Orinion** [comment]
What exactly is your problem? At what step are you?
you "simply" use this Burpsuite extension to decrypt it.

**Comment by ZRginger** [comment]
> What exactly is your problem? At what step are you?
> you "simply" use this Burpsuite extension to decrypt it.
I mean I have no idea where the aescbcencrypt is. I can't find it. Sorry for my English..

**Comment by ZRginger** [comment]
I know I can get aescbcencrypt outgoing message from there:
![image](https://user-images.githubusercontent.com/34329573/54347768-a0dc5d80-4682-11e9-9135-df8ce29d5431.png)

Right? And how I don't know how to send  changed outgoing message to peer...

**Comment by Orinion** [comment]
first click on 
![grafik](https://user-images.githubusercontent.com/12730894/54362126-b04ead00-4668-11e9-8e2e-1c493649916b.png) (nex to "Line") to make it readable.

Then enter the messsage you want to send.

Then (before sending it) set the breakpoint by clicking on the line number.

Then click the send button.

**Comment by ZRginger** [comment]
> first click on
> ![grafik](https://user-images.githubusercontent.com/12730894/54362126-b04ead00-4668-11e9-8e2e-1c493649916b.png) (nex to "Line") to make it readable.
> 
> Then enter the messsage you want to send.
> 
> Then (before sending it) set the breakpoint by clicking on the line number.
> 
> Then click the send button.

I know it. What I want to say is how can I send the changed outgoing message(I take the out message and change it and encrypt it again) to peer. Sorry for my English again. I hope  you can understand what I said.
Emm...  more specifically how could I change the value of 'a' on local.
