### ISSUE TITLE
Upgrade from Python 2.7 to Python 3.7?

### ISSUE THREAD

**Issue by cclauss** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#5]
[flake8](http://flake8.pycqa.org) testing of https://github.com/romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./burpWhatsapp.py:186:36: E999 SyntaxError: invalid syntax
                    print serverData
                                   ^
./helper/parser.py:169:34: E999 SyntaxError: invalid syntax
        print "ENCRYPTED DIFF: {}".format(char_diff)
                                 ^
./helper/libs/whatsapp_write.py:178:21: E999 SyntaxError: invalid syntax
            print int(value, 16)
                    ^
3     E999 SyntaxError: invalid syntax
3
```

**Comment by romanzaikin** [comment]
We wrote the tool in python 2.7 we currently not planning to convert it to python 3.
by the way you can do that your self easily and your errors is just a missing brackets in the print functions.
