### ISSUE TITLE
I have the private, public key and Secret. How do I get the RefObject

### ISSUE THREAD

**Issue by fuxf1984** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#50]
I have the secret, but how can I recieve the human readable string ref object from it? It seems like some kind of hash.
When I take a look at the screenshots of the blog and users there is also a hash as secret and no plain text. What am I doing wrong?

Thanks for the help!

**Comment by fuxf1984** [comment]
I have found the ref Object. Don't know why I missed it the first time.

**Comment by fuxf1984** [comment]
Ok seems like my Ref Object is wrong. I can't Decrypt or Encrypt and cursor always jumps in Line of Ref Object. What part of the string do I have to paste as Ref Object? With Secret, only the Phone part?

**Comment by sugarjohnny** [comment]
Did u fix it

**Comment by Kirubakaran786** [comment]
@romanzaikin @thiru112 which part of ref I'll to pass..... I have only this ws in my network tab in crome
![Uploading 15936021312144065687639873161031.jpg…]()

**Comment by Kirubakaran786** [comment]
@romanzaikin @thiru112 which part of ref I'll to pass..... I have only this ws in my network tab in ch
![15936023122511329622811974939124](https://user-images.githubusercontent.com/60040646/86238258-d16b4200-bbba-11ea-82c3-8f2a53a0d92b.jpg)
rome
