### ISSUE TITLE
Where are the keys? What am I doing wrong..

### ISSUE THREAD

**Issue by Michiel4211** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#51]
![what](https://user-images.githubusercontent.com/25084742/62827744-c344b980-bbd5-11e9-8bbb-c7440e05884c.png)

**Comment by thiru112** [comment]
@Michiel4211 Actually you are in right track, Now actually you should see the privkey and pubkey. Today morning i also tried doing the same thing, but i too did'nt get keys. I don't know that whatsapp patched this vulnerability. 

May be @romanzaikin can help us.!!

**Comment by sanyogthescholar** [comment]
I also can't seem to find the keys. Has Whatsapp patched this?

**Comment by sugarjohnny** [comment]
Hi guys i got the keys but its no longer stored there. Break the code on var t=l.keyPair() and you will get the keys

**Comment by Michiel4211** [comment]
> Hi guys i got the keys but its no longer stored there. Break the code on var t=l.keyPair() and you will get the keys

Lol, now my breakpoint doesnt work and just loads.. 
![Untitled3](https://user-images.githubusercontent.com/25084742/62832843-244faa00-bc35-11e9-947c-2b8ac327ee7e.png)

**Comment by Michiel4211** [comment]
> Hi guys i got the keys but its no longer stored there. Break the code on var t=l.keyPair() and you will get the keys

I managed to pause it, I now have this:
![Untitled1](https://user-images.githubusercontent.com/25084742/62833019-2bc48280-bc38-11e9-8098-a27e11e99da0.png)

Where are the keys?

**Comment by Michiel4211** [comment]
> > Hi guys i got the keys but its no longer stored there. Break the code on var t=l.keyPair() and you will get the keys
> 
> I managed to pause it, I now have this:
> 
> Where are the keys?
