### ISSUE TITLE
cannot decrypt message even with ref keys and base 64 encoded message.

### ISSUE THREAD

**Issue by sugarjohnny** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#52]
![Capture](https://user-images.githubusercontent.com/53993933/62833597-1f5e1b00-bc74-11e9-8f15-53d587ff694a.PNG)
what am i doing wrong

**Comment by sugarjohnny** [comment]
i dont know what the message tag function is for

**Comment by sugarjohnny** [comment]
Heeelp

**Comment by sanyogthescholar** [comment]
I have the same issue. Can anyone please help us?

**Comment by marcinguy** [comment]
Did you guys capture the Priv and Pub key before QR generation? What lines did you break on?

Can you describe your procedure step by step.

BTW Have same problem here. Used correct Ref Object (secret), Private Key and Public Key (I think I capture it after QR generation). Copied Payload from Proxy capture and base64encoded it and get the same messages for several messages (with different Message Tags).

It is tricky to get the Priv and Pub key, so I assume I got the wrong one.

**Comment by sugarjohnny** [comment]
guys i solved it just make sure that the reference is correct, i realised my ref obj had an extra character
also i realised that changing the number to some random thing crashes the chat for EVERYONE

**Comment by sajukassim** [comment]
> guys i solved it just make sure that the reference is correct, i realised my ref obj had an extra character
> also i realised that changing the number to some random thing crashes the chat for EVERYONE

Hi, How do you get the  Ref Object. I got the private and Pub Key

**Comment by sugarjohnny** [comment]
Setup burpsuite as a proxy server, install certs connect to the proxy server and scan the qr code while intercept is on

**Comment by sajukassim** [comment]
> Setup burpsuite as a proxy server, install certs connect to the proxy server and scan the qr code while intercept is on

Thanks got the Ref Obj
