### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by shahsidd** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#53]
No module named burp
![error](https://user-images.githubusercontent.com/21016880/62835190-d8bbf100-bc72-11e9-90ba-b69d1af0d09b.png)

**Comment by thiru112** [comment]
First of all you need to install burpsuite community edition.

You have to important this extension into burpsuite not in Python IDLE. Please read the README file properly.

**Comment by romanzaikin** [comment]
This is a Burp Suite plugin not a standalone script
