### ISSUE TITLE
parser.py doesn't work

### ISSUE THREAD

**Issue by BenIzhak** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#6]
Hello,
When I run parser.py it just prints "Waiting for connection" and the credits and than nothing happens.
There is something I should do after that to make it works?
Thank you.

**Comment by Jezwin** [comment]
While running burpWhatsapp.py it comes up with,
**_Traceback (most recent call last):
  File "burpWhatsapp.py", line 1, in <module>
    from burp import IBurpExtender, ITab
ImportError: No module named burp_**

**Comment by romanzaikin** [comment]
@BenIzhak yes you should install the `burpWhatsapp.py` extension to your burp suit.
@Jezwin the file `burpWhatsapp.py` is a burpsuit extension, not a standalone script...

**Comment by BenIzhak** [comment]
@romanzaikin I already installed it.
Maybe there's other reason?
Thank you for the response.

**Comment by ganeshjadhav23** [comment]
How to get private and public keys?

**Comment by romanzaikin** [comment]
@ganeshjadhav23 read our blog: 
https://research.checkpoint.com/fakesapp-a-vulnerability-in-whatsapp/

**Comment by ganeshjadhav23** [comment]
@romanzaikin 
But there is no explanation how to get Key's

**Comment by Jezwin** [comment]
Could you just help me how to install and run burpsuit in debian? I've gone
through the blog and all that listed in README file. But I missed something
I guess.

**Comment by romanzaikin** [comment]
@ganeshjadhav23 in the blog we have the section `Accessing the Keys` this is not that simple, you have to understand a little about Debugging and how to get the keys from there. 

This is just an advance tool that can decrypt & encrypt the communication for you, and from there you can read what we did or find more bugs by your own :)

**Comment by gunscrypto** [comment]
Hi, i can't install the curve25519-donna; it shows a initial error 

 Running setup.py bdist_wheel for curve25519-donna ... error

and after that it shows some errors regarding the syntax like...

curve25519-donna.c(99) : error C2059: syntax error : ')'
  curve25519-donna.c(99) : error C2054: expected '(' to follow 'in'
  curve25519-donna.c(206) : error C2143: syntax error : missing ')' before '*'
  curve25519-donna.c(206) : error C2143: syntax error : missing '{' before '*'
  curve25519-donna.c(206) : error C2059: syntax error : ')'

do you have any suggestions??

Regards!!.

**Comment by romanzaikin** [comment]
@gunscrypto sorry never encounter this error, are you using python 2.7? and did everything according to my readme?

**Comment by Banginpadr** [comment]
can some one guide me on getting the keys? i have been trying for 3 days and nothing. can i also know what debugger are you using?

**Comment by romanzaikin** [comment]
@Banginpadr Chrome Developer tools (just press F12)...

**Comment by ganeshjadhav23** [comment]
![whatsapp image 2018-08-10 at 11 28 15 am](https://user-images.githubusercontent.com/22657479/43941179-b5d91202-9c62-11e8-959d-5285b533cbea.jpeg)
Done ! 
OS= kali 4.15.0-kali2-amd64

**Comment by romanzaikin** [comment]
@ganeshjadhav23 well done :)

**Comment by thiru112** [comment]
@ganeshjadhav23  How do u got ref obj ?? though intercept i cant get it . proxy at 127.0.0.1 port 8080
and also imported Burp Suite cert in chrome. Help me pls

**Comment by ganeshjadhav23** [comment]
@thiru112 which os use use?
if you are using kali then type in terminal google-chrome --proxy-server="127.0.0.1:8080"
then your interception is start

**Comment by thiru112** [comment]
@ganeshjadhav23 I use ubuntu 18.04LTS same config only, but not even a single entry in **websockets**  history tab 

But I started try things in  **Windows 7**  then it worked completely fine.I don't know what problem with browser in Ubuntu

**Comment by thiru112** [comment]
@ganeshjadhav23 thanks bro now it is working

I set up proxy manually in setting
