### ISSUE TITLE
Can't start parser server

### ISSUE THREAD

**Issue by sahilvinodMhatre** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#60]
whenever I try to run parser.py it does not start every time a error is displayed that is shown below
`C:\Users\Adminn\Desktop\BurpExtension-WhatsApp-Decryption-CheckPoint-master\helper>python parser.py
  File "parser.py", line 178
    print "ENCRYPTED DIFF: {}".format(char_diff)
                             ^
SyntaxError: invalid syntax
`
plz help me to get out of this

**Comment by darkane188** [comment]
> cada vez que intento ejecutar parser.py no se inicia cada vez que se muestra un error que se muestra a continuación, por
> `C:\Users\Adminn\Desktop\BurpExtension-WhatsApp-Decryption-CheckPoint-master\helper>python parser.py File "parser.py", line 178 print "ENCRYPTED DIFF: {}".format(char_diff) ^ SyntaxError: invalid syntax `
> favor, ayúdame a salir de esto

change for this
 print ("ENCRYPTED DIFF: {}".format(char_diff))
