### ISSUE TITLE
parser.py doesn't work

### ISSUE THREAD

**Issue by Aledangelo** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#63]
When I start parser.py using pyhton 2.7.18 it show me this message

Traceback (most recent call last):
  File "parser.py", line 3, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher

I have already installed pycrypto library (pip install pycrypto)

**Comment by Alireza-Razavi** [comment]
@Aledangelo You should install it as BuroSuite extension.
Have you found the public key and private key in whatsapp web (using browser inspector) ??
Where is it (in which javascript file) ??

**Comment by chrisrusso** [comment]
pip install with --upgrade --forcer-reinstall <pkg> to everything that is failing.

**Comment by Aledangelo** [comment]
Thanks, I will try it
