### ISSUE TITLE
unexpected public/private keys

### ISSUE THREAD

**Issue by snakeeater0x01** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#66]
hi!
hope u have a wonderful time.

i have a question 
Am I wrong about something here, because i cant find the privat/public key as it’s expected
<img width="1213" alt="Screen Shot 2022-02-10 at 8 33 03 PM" src="https://user-images.githubusercontent.com/72659246/153484435-20647f34-7ebe-467d-9975-6ec8e18d9d4e.png">

**Comment by cuj** [comment]
May I ask, which file did you open in the sources tab, in DevTools?

**Comment by cuj** [comment]
Also I think that clicking on the triangle arrow ⏵ before the `[[Uint8Array]]: Uint8Array(32)` in both pubKey and privKey should show the keys.
