### ISSUE TITLE
Not able to run parse.py file 

### ISSUE THREAD

**Issue by Pabla007** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#7]
I am have this error while compiling 
windows 32 bit python 3.6 anaconda
![capture](https://user-images.githubusercontent.com/35897183/43919332-3aa813be-9c33-11e8-803d-4ede46b43abd.PNG)

**Comment by romanzaikin** [comment]
just follow the readme, I didn't test it with anaconda... and python 3.6
